In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path
import zipfile

In [2]:
PROJECT_PATH = Path.cwd().parent
print("Project_Path", PROJECT_PATH.resolve())

Project_Path C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis

In [3]:
RAW_PATH = PROJECT_PATH / "01_Raw_Data"
RAW_PATH.mkdir(parents=True, exist_ok=True)
print("Raw_Path", RAW_PATH.resolve())

DOCUMENTATION_PATH = PROJECT_PATH / "02_Documentation"
DOCUMENTATION_PATH.mkdir(parents=True, exist_ok=True)
print("Documentation_Path", DOCUMENTATION_PATH.resolve())

Raw_Path C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data
Documentation_Path C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\02_Documentation

In [4]:
RD_2024 = RAW_PATH / "2024"
RD_2024.mkdir(parents=True, exist_ok=True)
print("Raw_Data_2024", RD_2024.resolve())

RD_2025 = RAW_PATH / "2025"
RD_2025.mkdir(parents=True, exist_ok=True)
print("Raw_Data_2025", RD_2025.resolve())

Raw_Data_2024 C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024
Raw_Data_2025 C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025

In [5]:
EXTRACTED_FILES = RAW_PATH / "Extracted_Files"
EXTRACTED_FILES.mkdir(parents=True, exist_ok=True)
print("Extracted_Files_Path", EXTRACTED_FILES.resolve())

Extracted_Files_Path C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files

In [6]:
def extract_zip_files(folder_name):
    for zip_path in folder_name.glob("*.zip"):
        print("Extracting: ", zip_path.name)

        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            zip_ref.extractall(EXTRACTED_FILES)

    print("Completed: ", folder_name.name)

In [7]:
extract_zip_files(RD_2024)
extract_zip_files(RD_2025)

Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_1.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_10.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_11.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_12.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_2.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_3.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_4.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_5.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_6.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_7.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_8.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_9.zip
Completed:  2024
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_1.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_10.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_11.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_12.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_2.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_3.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_4.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_5.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_6.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_7.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_8.zip
Extracting:  On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_9.zip
Completed:  2025

In [ ]:
total_zip_files = len(list(RD_2024.glob("*.zip"))) + len(list(RD_2025.glob("*.zip")))
print("Total ZIP files in Raw Data: ", total_zip_files)
total_csv_files = len(list(EXTRACTED_FILES.glob("*.csv")))
print("Total CSV files in Raw Data: ", total_csv_files)

print()

total_zip_files = len(list(RD_2024.glob("*.zip")))
print("Total ZIP files in 2024: ", total_zip_files)
total_zip_files = len(list(RD_2025.glob("*.zip")))
print("Total ZIP files in 2025: ", total_zip_files)

print()

for zip_file in list(RD_2024.glob("*.zip")) + list(RD_2025.glob("*.zip")):
    print("ZIP file", zip_file.name)
    print("Size", zip_file.stat().st_size / (1024 * 1024), "MB")
    print("Last Modified", zip_file.stat().st_mtime)
    print("File Location", zip_file.resolve())
    print()

Total ZIP files in Raw Data:  24
Total CSV files in Raw Data:  24

Total ZIP files in 2024:  12
Total ZIP files in 2025:  12

ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_1.zip
Size 26.29591464996338 MB
Last Modified 1788156549.1879227
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_1.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_10.zip
Size 28.055623054504395 MB
Last Modified 1788156549.2893374
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_10.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_11.zip
Size 26.84531593322754 MB
Last Modified 1788156549.3886728
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_11.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_12.zip
Size 28.753633499145508 MB
Last Modified 1788156549.4956226
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_12.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_2.zip
Size 23.9246883392334 MB
Last Modified 1788156549.5889664
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_2.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_3.zip
Size 27.955687522888184 MB
Last Modified 1788156549.6892085
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_3.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_4.zip
Size 27.21842670440674 MB
Last Modified 1788156549.7892363
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_4.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_5.zip
Size 29.697324752807617 MB
Last Modified 1788156549.8919947
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_5.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_6.zip
Size 29.780159950256348 MB
Last Modified 1788156550.0111165
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_6.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_7.zip
Size 32.83231163024902 MB
Last Modified 1788156550.130461
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_7.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_8.zip
Size 29.42515468597412 MB
Last Modified 1788156550.2255852
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_8.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_9.zip
Size 27.11675453186035 MB
Last Modified 1788156550.3372784
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2024\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2024_9.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_1.zip
Size 25.85283660888672 MB
Last Modified 1788156550.4334376
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_1.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_10.zip
Size 29.300501823425293 MB
Last Modified 1788156550.545166
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_10.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_11.zip
Size 27.51136302947998 MB
Last Modified 1788156550.6408136
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_11.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_12.zip
Size 28.932028770446777 MB
Last Modified 1788156550.7500806
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_12.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_2.zip
Size 24.130423545837402 MB
Last Modified 1788156550.8299165
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_2.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_3.zip
Size 29.129815101623535 MB
Last Modified 1788156550.9416487
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_3.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_4.zip
Size 28.008638381958008 MB
Last Modified 1788156551.055023
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_4.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_5.zip
Size 29.402344703674316 MB
Last Modified 1788156551.148237
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_5.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_6.zip
Size 29.68922710418701 MB
Last Modified 1788156551.2751336
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_6.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_7.zip
Size 30.71661376953125 MB
Last Modified 1788156551.37123
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_7.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_8.zip
Size 29.43443775177002 MB
Last Modified 1788156551.482299
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_8.zip
ZIP file On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_9.zip
Size 26.84748649597168 MB
Last Modified 1788156551.5931165
File Location C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\2025\On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2025_9.zip

In [9]:
csv_files = list(EXTRACTED_FILES.glob("*.csv"))

print("Total CSV files:", len(csv_files))
print()

for file in csv_files:
    print(file)

Total CSV files: 24

c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_10.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_11.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_12.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_4.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_5.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_6.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_7.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_8.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_9.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

In [10]:
dfs = []

for file in csv_files:
    df = pd.read_csv(
        file,
        low_memory=False
    )
    dfs.append(df)

print("Total Files:", len(dfs))

Total Files: 24

In [11]:
for i, df in enumerate(dfs, start=1):
    print("File: ", i)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print()

File:  1
Rows: 547271
Columns: 110

File:  2
Rows: 615497
Columns: 110

File:  3
Rows: 575404
Columns: 110

File:  4
Rows: 590581
Columns: 110

File:  5
Rows: 519221
Columns: 110

File:  6
Rows: 591767
Columns: 110

File:  7
Rows: 582185
Columns: 110

File:  8
Rows: 609743
Columns: 110

File:  9
Rows: 611132
Columns: 110

File:  10
Rows: 634613
Columns: 110

File:  11
Rows: 619025
Columns: 110

File:  12
Rows: 582622
Columns: 110

File:  13
Rows: 539747
Columns: 110

File:  14
Rows: 605844
Columns: 110

File:  15
Rows: 570550
Columns: 110

File:  16
Rows: 582304
Columns: 110

File:  17
Rows: 504884
Columns: 110

File:  18
Rows: 600872
Columns: 110

File:  19
Rows: 583950
Columns: 110

File:  20
Rows: 605648
Columns: 110

File:  21
Rows: 611575
Columns: 110

File:  22
Rows: 631428
Columns: 110

File:  23
Rows: 602378
Columns: 110

File:  24
Rows: 562439
Columns: 110

In [14]:
for i, df in enumerate(dfs, start=1):
    print("File: ", i)
    print(df.info())
    print()

File:  1
<class 'pandas.DataFrame'>
RangeIndex: 547271 entries, 0 to 547270
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(68), int64(21), str(21)
memory usage: 459.3 MB
None

File:  2
<class 'pandas.DataFrame'>
RangeIndex: 615497 entries, 0 to 615496
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 516.5 MB
None

File:  3
<class 'pandas.DataFrame'>
RangeIndex: 575404 entries, 0 to 575403
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 482.9 MB
None

File:  4
<class 'pandas.DataFrame'>
RangeIndex: 590581 entries, 0 to 590580
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 495.6 MB
None

File:  5
<class 'pandas.DataFrame'>
RangeIndex: 519221 entries, 0 to 519220
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 435.7 MB
None

File:  6
<class 'pandas.DataFrame'>
RangeIndex: 591767 entries, 0 to 591766
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 496.6 MB
None

File:  7
<class 'pandas.DataFrame'>
RangeIndex: 582185 entries, 0 to 582184
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 488.6 MB
None

File:  8
<class 'pandas.DataFrame'>
RangeIndex: 609743 entries, 0 to 609742
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 511.7 MB
None

File:  9
<class 'pandas.DataFrame'>
RangeIndex: 611132 entries, 0 to 611131
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 512.9 MB
None

File:  10
<class 'pandas.DataFrame'>
RangeIndex: 634613 entries, 0 to 634612
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(71), int64(20), str(19)
memory usage: 532.6 MB
None

File:  11
<class 'pandas.DataFrame'>
RangeIndex: 619025 entries, 0 to 619024
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(72), int64(20), str(18)
memory usage: 519.5 MB
None

File:  12
<class 'pandas.DataFrame'>
RangeIndex: 582622 entries, 0 to 582621
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 489.0 MB
None

File:  13
<class 'pandas.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 453.0 MB
None

File:  14
<class 'pandas.DataFrame'>
RangeIndex: 605844 entries, 0 to 605843
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 508.4 MB
None

File:  15
<class 'pandas.DataFrame'>
RangeIndex: 570550 entries, 0 to 570549
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 478.8 MB
None

File:  16
<class 'pandas.DataFrame'>
RangeIndex: 582304 entries, 0 to 582303
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(68), int64(21), str(21)
memory usage: 488.7 MB
None

File:  17
<class 'pandas.DataFrame'>
RangeIndex: 504884 entries, 0 to 504883
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(69), int64(21), str(20)
memory usage: 423.7 MB
None

File:  18
<class 'pandas.DataFrame'>
RangeIndex: 600872 entries, 0 to 600871
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 504.3 MB
None

File:  19
<class 'pandas.DataFrame'>
RangeIndex: 583950 entries, 0 to 583949
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 490.1 MB
None

File:  20
<class 'pandas.DataFrame'>
RangeIndex: 605648 entries, 0 to 605647
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 508.3 MB
None

File:  21
<class 'pandas.DataFrame'>
RangeIndex: 611575 entries, 0 to 611574
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(68), int64(21), str(21)
memory usage: 513.3 MB
None

File:  22
<class 'pandas.DataFrame'>
RangeIndex: 631428 entries, 0 to 631427
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 529.9 MB
None

File:  23
<class 'pandas.DataFrame'>
RangeIndex: 602378 entries, 0 to 602377
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 505.5 MB
None

File:  24
<class 'pandas.DataFrame'>
RangeIndex: 562439 entries, 0 to 562438
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(71), int64(20), str(19)
memory usage: 472.0 MB
None

combined csv file

In [15]:
total_memory = sum(
    df.memory_usage(deep=True).sum()
    for df in dfs
)

print(
    "Current DataFrames memory:",
    round(total_memory / (1024**3), 2),
    "GB"
)

Current DataFrames memory: 21.91 GB

In [16]:
del dfs

In [17]:
import gc
gc.collect()

0

In [18]:
sample_df = pd.read_csv(csv_files[0], low_memory=False)

print(sample_df.shape)
sample_df.info()

(547271, 110)
<class 'pandas.DataFrame'>
RangeIndex: 547271 entries, 0 to 547270
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(68), int64(21), str(21)
memory usage: 459.3 MB

In [19]:
sample_df.select_dtypes(include="str").columns.tolist()
sample_df.select_dtypes(include="str").nunique().sort_values()

Div3TailNum                       1
Div3Airport                       1
CancellationCode                  3
Reporting_Airline                15
IATA_CODE_Reporting_Airline      15
DepTimeBlk                       19
ArrTimeBlk                       19
Div2Airport                      20
Div2TailNum                      21
FlightDate                       31
OriginState                      52
OriginStateName                  52
DestState                        52
DestStateName                    52
Div1Airport                     169
OriginCityName                  328
DestCityName                    328
Origin                          334
Dest                            334
Div1TailNum                    1082
Tail_Number                    5604
dtype: int64

In [20]:
import psutil

ram = psutil.virtual_memory()

print("Total RAM:", round(ram.total / (1024**3), 2), "GB")
print("Available RAM:", round(ram.available / (1024**3), 2), "GB")

Total RAM: 15.73 GB
Available RAM: 7.85 GB

In [22]:

del sample_df

In [23]:
import gc

gc.collect()

432

In [24]:
ram = psutil.virtual_memory()

print("Available RAM:", round(ram.available / (1024**3), 2), "GB")

Available RAM: 8.12 GB

In [25]:
total_size = sum(
    file.stat().st_size for file in csv_files
)

print(
    "Total CSV size:",
    round(total_size / (1024**3), 2),
    "GB"
)

Total CSV size: 5.93 GB

In [26]:
combined_file = EXTRACTED_FILES / "combined_flights_2024_2025.csv"

first_file = True

for file in csv_files:
    print("Processing:", file.name)

    for chunk in pd.read_csv(file, chunksize=100_000, low_memory=False):
        chunk.to_csv(
            combined_file,
            mode="w" if first_file else "a",
            index=False,
            header=first_file
        )
        first_file = False

print("Combined CSV created:", combined_file)

Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_10.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_11.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_12.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_4.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_5.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_6.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_7.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_8.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_9.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Processing: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Combined CSV created: c:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\combined_flights_2024_2025.csv

In [27]:
print("File:", combined_file.name)
print("Size:", round(combined_file.stat().st_size / (1024**3), 2), "GB")
print("Location:", combined_file.resolve())

File: combined_flights_2024_2025.csv
Size: 4.77 GB
Location: C:\Continental__Skies-Delay_Root_Cause_and_Reliability_Analysis\01_Raw_Data\Extracted_Files\combined_flights_2024_2025.csv

In [29]:
df_sample = pd.read_csv(
    combined_file,
    nrows=5,
    low_memory=False
)

df_sample.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2024,1,1,8,1,2024-01-08,9E,20363,9E,N485PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9,2,2024-01-09,9E,20363,9E,N912XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,10,3,2024-01-10,9E,20363,9E,N918XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,11,4,2024-01-11,9E,20363,9E,N490PX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,12,5,2024-01-12,9E,20363,9E,N915XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_sample.shape

(5, 110)

In [32]:
df_sample.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [33]:
total_rows = 0

for chunk in pd.read_csv(
    combined_file,
    chunksize=100_000,
    low_memory=False
):
    total_rows += len(chunk)

print("Total rows:", total_rows)

Total rows: 14080680

In [34]:
missing_values = None

for chunk in pd.read_csv(
    combined_file,
    chunksize=100_000,
    low_memory=False
):
    current_missing = chunk.isna().sum()

    if missing_values is None:
        missing_values = current_missing
    else:
        missing_values = missing_values.add(
            current_missing,
            fill_value=0
        )

print("Overall Missing Values:")
print(missing_values)

Overall Missing Values:
Year                       0
Quarter                    0
Month                      0
DayofMonth                 0
DayOfWeek                  0
                      ...
Div5TotalGTime      14080680
Div5LongestGTime    14080680
Div5WheelsOff       14080680
Div5TailNum         14080680
Unnamed: 109        14080680
Length: 110, dtype: int64

In [35]:
missing_table = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": (missing_values / total_rows) * 100
})

missing_table = missing_table.sort_values(
    "Missing Percentage",
    ascending=False
)

missing_table

                  Missing Values  Missing Percentage
Div5WheelsOff           14080680               100.0
Div5LongestGTime        14080680               100.0
Div5TotalGTime          14080680               100.0
Div5WheelsOn            14080680               100.0
Div5AirportSeqID        14080680               100.0
...                          ...                 ...
ArrTimeBlk                     0                 0.0
Distance                       0                 0.0
DistanceGroup                  0                 0.0
Cancelled                      0                 0.0
Diverted                       0                 0.0

[110 rows x 2 columns]

In [36]:
empty_columns = missing_table[
    missing_table["Missing Values"] == total_rows
]

print("Completely empty columns:", len(empty_columns))
display(empty_columns)

Completely empty columns: 17

                  Missing Values  Missing Percentage
Div5WheelsOff           14080680               100.0
Div5LongestGTime        14080680               100.0
Div5TotalGTime          14080680               100.0
Div5WheelsOn            14080680               100.0
Div5AirportSeqID        14080680               100.0
Div5AirportID           14080680               100.0
Div5Airport             14080680               100.0
Div4TailNum             14080680               100.0
Div4WheelsOff           14080680               100.0
Div4LongestGTime        14080680               100.0
Div4TotalGTime          14080680               100.0
Div4WheelsOn            14080680               100.0
Div4AirportSeqID        14080680               100.0
Div4AirportID           14080680               100.0
Unnamed: 109            14080680               100.0
Div5TailNum             14080680               100.0
Div4Airport             14080680               100.0

In [37]:
original_total_rows = 0

for file in csv_files:
    rows = 0

    for chunk in pd.read_csv(file, chunksize=100_000, low_memory=False):
        rows += len(chunk)

    print(file.name, "->", rows, "rows")
    original_total_rows += rows

print("\nTotal rows in original CSV files:", original_total_rows)

On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv -> 547271 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_10.csv -> 615497 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_11.csv -> 575404 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_12.csv -> 590581 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv -> 519221 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv -> 591767 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_4.csv -> 582185 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_5.csv -> 609743 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_6.csv -> 611132 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_7.csv -> 634613 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_8.csv -> 619025 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_9.csv -> 582622 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv -> 539747 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv -> 605844 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv -> 570550 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv -> 582304 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv -> 504884 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv -> 600872 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv -> 583950 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv -> 605648 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv -> 611575 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv -> 631428 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv -> 602378 rows
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv -> 562439 rows

Total rows in original CSV files: 14080680

In [38]:
combined_total_rows = 0

for chunk in pd.read_csv(combined_file, chunksize=100_000, low_memory=False):
    combined_total_rows += len(chunk)

print("Original CSV total rows :", original_total_rows)
print("Combined CSV total rows :", combined_total_rows)

if original_total_rows == combined_total_rows:
    print("✅ Row counts match. No rows were lost during combining.")
else:
    print("❌ Row counts do not match.")
    print("Difference:", original_total_rows - combined_total_rows)

Original CSV total rows : 14080680
Combined CSV total rows : 14080680
✅ Row counts match. No rows were lost during combining.

In [39]:
original_missing = None

for file in csv_files:
    print("Checking:", file.name)

    for chunk in pd.read_csv(file, chunksize=100_000, low_memory=False):
        current_missing = chunk.isna().sum()

        if original_missing is None:
            original_missing = current_missing
        else:
            original_missing = original_missing.add(
                current_missing,
                fill_value=0
            )

print("Original files checked.")

Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_10.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_11.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_12.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_4.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_5.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_6.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_7.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_8.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_9.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Checking: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Original files checked.

In [40]:
combined_missing = None

for chunk in pd.read_csv(combined_file, chunksize=100_000, low_memory=False):
    current_missing = chunk.isna().sum()

    if combined_missing is None:
        combined_missing = current_missing
    else:
        combined_missing = combined_missing.add(
            current_missing,
            fill_value=0
        )

print("Combined file checked.")

Combined file checked.

In [41]:
missing_comparison = pd.DataFrame({
    "Original Missing": original_missing,
    "Combined Missing": combined_missing
})

missing_comparison["Difference"] = (
    missing_comparison["Combined Missing"]
    - missing_comparison["Original Missing"]
)

display(missing_comparison)

                  Original Missing  Combined Missing  Difference
Year                             0                 0           0
Quarter                          0                 0           0
Month                            0                 0           0
DayofMonth                       0                 0           0
DayOfWeek                        0                 0           0
...                            ...               ...         ...
Div5TotalGTime            14080680          14080680           0
Div5LongestGTime          14080680          14080680           0
Div5WheelsOff             14080680          14080680           0
Div5TailNum               14080680          14080680           0
Unnamed: 109              14080680          14080680           0

[110 rows x 3 columns]